---
kind: pipeline
name: aarch64

platform:
  os: linux
  arch: arm64

clone:
  depth: 16

steps:
  - name: build
    image: arm64v8/alpine:latest
    commands: [./.drone.sh build]
  - name: check
    image: arm64v8/alpine:latest
    commands: [./.drone.sh check]
    when:
      event: pull_request

trigger:
  event: [push, pull_request, tag]
