name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run on Architecture
      uses: uraimo/run-on-arch-action@v1.0.9
      with:
        # Architecture type: armv6,armv7,aarch64,s390x,ppc64le
        architecture: aarch64 # optional, default is arm64v8
        # OS distribution name: ubuntu16.04, ubuntu18.04, buster, stretch, jessie
        distribution: ubuntu18.04 # optional, default is ubuntu:18.04
        # Additional arguments to add to docker run
        #additionalArgs: # optional
        # Command/s to execute
        run: "apt install make binutils build-dep libncurses-dev flex bison openssl libssl-dev libelf-dev libudev-dev libpci-dev libiberty-dev autoconf && make montana_defconfig && make"
